blog1/accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name='signup'),
]

blog1/blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView, TopicListView

urlpatterns = [
    path("post/<int:pk>/", BlogDetailView.as_view(), name="post_detail"),
    path("", BlogListView.as_view(), name="home"),
    path("post/new/", BlogCreateView.as_view(), name="post_new"),
    path("post/<int:pk>/edit/", BlogUpdateView.as_view(), name="post_edit"),
    path("post/<int:pk>/delete/", BlogDeleteView.as_view(), name="post_delete"),
    path("topic", TopicListView.as_view(), name="topic"),
]

blog1/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls")),
    path("accounts", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog1/accounts/models.py
from django.db import models

# Create your models here.

blog1/blog/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
class Topic(models.Model):
    topic = models.CharField(max_length=20)
    def __str__(self):
        return self.topic 
    
class Post(models.Model):
    title = models.CharField(max_length=50)
    author = models.ForeignKey(
        "auth.User", # this provides for user authentication
        on_delete=models.CASCADE, 
        )
    body = models.TextField()
    def __str__(self): # this provides for a readable model in the admin shell
        return self.title
    def get_absolute_url(self): # this builds a URL address for a model object
        return reverse("post_detail", kwargs={"pk": self.pk}) 
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT,default='1')
    date = models.DateField(auto_now_add=True, )
    image = models.ImageField(null=True, blank=True,
    upload_to="images/")


       


blog1/accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

blog1/blog/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Topic
from django.urls import reverse_lazy


class BlogListView(ListView):
    model = Post
    template_name = "home.html"

class BlogDetailView(DetailView):
    model = Post
    template_name = "post_detail.html"

class BlogCreateView(CreateView):
    model = Post
    template_name = "post_new.html"
    fields = ["title", "topic", "body", "image"]

    def form_valid(self, form):
        form.instance.author =self.request.user
        return super().form_valid(form)

class BlogUpdateView(UpdateView):
    model = Post
    template_name = "post_edit.html"
    fields = ["title", "topic", "body", "image"]  

class BlogDeleteView(DeleteView):
    model = Post
    template_name = "post_delete.html"
    success_url = reverse_lazy("home") 

class TopicListView(ListView):
    model = Topic
    template_name = "topic.html"

blog1/templates/base.html
{% load static %}
<html>

<head>
    <title>Plant Life</title>
    <link href="{% static 'base.css' %}" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <main>
    
    <header>
    <div class="homenav">
        <h1><a href = "{% url 'home' %}">Plant Life</a></h1>
    </div>

    <div class="new">
        {% if user.is_authenticated %}
        <a href="{% url 'post_new' %}">+ New Post</a>
        {% endif %}
    </div>

    <div class="topics">
        <a href="{% url 'topic' %}">Topics</a>
        {% if user.is_authenticated %}
        
        <a href="{% url 'logout' %}">Log Out</a>
        {% else %}
        
        <a href="{% url 'login' %}">Log In</a> 
        <a href="{% url 'signup' %}">Sign Up</a>
    {% endif %}
    </div>
    
    </div>
    </header>
    
    <br>

    {% if user.is_authenticated %}
    <p style="font-size:25px; text-align:center;"> Welcome {{user.username}}</p>
    
    {% else %}
    <p style="font-size:25px; text-align:center;">You are not logged in.</p>
    
    {% endif %}
    
    

    <div class="bodycontent">
    
    
    
        {% block content %} {% endblock content %}
    </div>
    </main>

    <footer> delaneydonaghy 2024</footer>
</body>

</html>

blog1/templates/home.html
{% extends "base.html" %}
 {% load static %}
{% block content %}

{% for post in post_list %}

    <div class="post-entry" >
        <p style="border: 2px grey solid; width: 400px; height: 400px; margin-right: 30px; float:left;">{% if post.image %}
            <img src="{{post.image.url}}" width=400px; height=400px;>
            {% endif %}</p>
        <div class="postinfo">
         <h2><a href = "{% url 'post_detail' post.pk %}">{{post.title}}</a></h2>
         <p style="font-size:20px;">{{post.body}}</p>
        </div>
    </div>
    <br>
    <br>


    
{% endfor %}


{% endblock content %}

blog1/templates/post_delete.html
{%  extends "base.html"  %}
{% load static %}
{%  block content  %}

<main style="width: 100%; position: relative;">
        <img src="{% static 'tree.jpg' %}" alt="background image large tree" width="100%" height="100%" style="opacity:0.5;">
<div class="deletion" style="position: absolute; top:50%; left:50%; transform:translate(-50%, -50%);">
{% if user.is_authenticated %}
{% if user.id == post.author.id %}

<h1>Delete post</h1>
<form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ post.title }}"?</p>
<input type="submit" value="Confirm">
</form >
</div>
{% else %}
You are not authorized to delete this blog!
{% endif %}

{% else %}
Please Log In
{% endif %}

</main>
{%  endblock content  %}

blog1/templates/post_detail.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<main style="width: 100%; height: 100%;">
<div class="post-entry">
    <p style="border: 2px grey solid; width: 400px; height: 400px; margin-right: 30px; float:left;">{% if post.image %}
        <img src="{{post.image.url}}" width=400px; height=400px;>
        {% endif %}</p>
    <h2>{{ post.title }}</h2>
    <p style="font-size:20px;">{{ post.author }}</p>
    <p style="font-size:20px;">topic: {{ post.topic }}</p>
    <p style="font-size:20px;">created: {{ post.date }}</p>
    <br>
    <p style="font-size:20px;">{{ post.body }}</p>
</div>

{% if user.is_authenticated %}
{% if user.id == post.author.id %}



        <div class="edit">
        <a href="{% url 'post_edit' post.pk %}">Edit</a>
        </div>

    <div class="delete" >
    <a href="{% url 'post_delete' post.pk %}">Delete</a>
    </div>

{% else %}
    <p style="padding: 20px; text-align: center;">You are not authorized to edit this blog!</p>
{% endif %}

{% else %}
    <p style="padding: 20px; text-align: center;">Please Log In</p>
{% endif %}
</main>
{% endblock content %}

blog1/templates/post_edit.html
{%  extends "base.html"  %}
{% load static %}
{%  block content  %}

{% if user.is_authenticated %}
{% if user.id == post.author.id %}
<main style="width: 100%; position: relative;">
        <img src="{% static 'pond.jpg' %}" alt="background image forest and pond" width="100%" height="100%" style="opacity:0.5;">
<div class="edits" style="position: absolute; top:50%; left:50%; transform:translate(-50%, -50%);">
        <h1>Edit post</h1>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
<input type="submit" value="Update">
</form >
</div>
{% else %}
        You are not authorized to edit this blog!
{% endif %}

{% else %}
        Please Log In
{% endif %}

</main>
{%  endblock content  %}

blog1/templates/post_new.html
{%  extends "base.html"  %}
{% load static %}
{%  block content  %}

<main style="width: 100%; position: relative;">
        <img src="{% static 'forest.jpg' %}" alt="background image rainforest" width="100%" height="100%" style="opacity:0.5;">
<div class="newpost" style="position: absolute; top:50%; left:50%; transform:translate(-50%, -50%);">
{% if user.is_authenticated %}
<h1>New post</h1>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
</form >
{% endif %}
</div>
</main>
{%  endblock content  %}

blog1/templates/topic.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<main style="width: 100%; height: 100%; position: relative;">
    <img src="{% static 'rainforest.jpg' %}" alt="background image rainforest" width="100%" height="100%" style="opacity:0.5;">
    <div class="topiclist" style="position: absolute; top:50%; left:50%; transform:translate(-50%, -50%);">
    <h1 style="color: green">Plant Life Topics</h1>
    <ul>
    {% for topic in topic_list %}
    <li style="list-style-type: none; font-size: 25px;color: black">Topic: {{ topic }} </li>
    <ol>
    {% for post in topic.post_set.all %}
    <div class="topicnav">
    <a href = "{% url 'post_detail' post.pk %}">
    <li style="font-size: 18px; color: rgb(89, 131, 89); ">{{post.title}}</li></a>
    </div>
    {% endfor %}
    </ol>
    <p></p>
    {% endfor %}
    </ul>
</div>
</main>

{% endblock content %}